Vladimir.makotkin table part
dataline-team/DATALINE pull request #13
Opened 2021-08-12 21:51 UTC by Vov11x

Add:
 - Row class implementation / test coverage;
 - Table class header;

Update:
 - Variant class methods(const modifier for getters);

2021-08-13 07:00 UTC, lucky-rydar requested changes
Some fixes.

Also add searching cell in table by column name

2021-08-13 07:00 UTC, lucky-rydar commented on src/Table.h
> +    bool getBoolItem(std::function<void()>);  // `std::function<...>` signature hasn't been defined yet
You dont need getbool getint etc.. because you have variant class

2021-08-13 07:00 UTC, lucky-rydar commented on src/Table.h
> +    void setItem(bool data, std::function<void()>);  // `std::function<...>` signature hasn't been defined yet
Here also add only set varian

2021-09-17 20:07 UTC, lucky-rydar reviewed
There some letters in functions names of Table class.
The code looks pretty good, i hope you have tested it and it works correctly.
As for select method, later it will he rewrote to run some query written from console

2021-09-17 20:07 UTC, lucky-rydar commented on src/Table.cpp
> +void Table::setTName(const std::string &new_table_name)
Why it is everywhere 'T' in the middle of name of function?

2021-09-20 18:37 UTC, Vov11x commented
> Some fixes.
> 
> Aslo add searching cell in table by column name

Done.

2021-09-20 18:38 UTC, Vov11x commented on src/Table.cpp
> +void Table::setTName(const std::string &new_table_name)
> Why it is everywhere 'T' in the middle of name of function?

Done.

2021-09-25 14:35 UTC, merged